[package]
name = "advent"
version = "0.1.0"
authors = ["tinaun <tinagma@gmail.com>"]
edition = "2018"

[dependencies]
itertools = "0.7"
permutohedron = "0.2"
serde_scan = "0.3"
serde = "1.0"
serde_derive = "1.0"
doubly = "1.1"